### PR TITLE
Use Swift metadata 'last-mod-timestamp' instead of 'timestamp'

### LINKED ISSUE #14: Use Swift metadata 'last-mod-timestamp' instead of 'timestamp'
Preservation script setup to test each object in the UAL OpenStack Swift instance to see if the object is present and not outdated with respect to the CWRC repo. The "outdated" object test is failing as 'last-mod-timestamp' instead of 'timestamp' metadata key should be used. The result, every object is downloaded from CWRC and updated in Swift each time the script is executed.

### PR DESCRIPTION
**Pull request by jefferya**
Fixes #14

- Fixes test to determine if the OpenStack Swift object is outdated with respect to the CWRC repository objects (use 'last-mod-timestamp' metadata key). 
- updates bundler version
- adds Ruby 2.4 to the Travis tests

A request for the metadata from the OpenStack Swift instance returns a key `last-mod-timestamp`
```
irb(main):056:0> p swift_file.metadata
{"project-id"=>"tpatt_f39b0d8f-ffb4-4e31-86d5-f8fbb90ac38c", "last-mod-timestamp"=>"2019-01-15T04:56:33.772Z", "aip-version"=>"1.0", "project"=>"CWRC", "promise"=>"bronze"}
=> {"project-id"=>"tpatt_f39b0d8f-ffb4-4e31-86d5-f8fbb90ac38c", "last-mod-timestamp"=>"2019-01-15T04:56:33.772Z", "aip-version"=>"1.0", "project"=>"CWRC", "promise"=>"bronze"}
```

### CODE REVIEW

File: cwrc_audit_report.rb [hunk 1]
```diff
@@ -93,9 +93,9 @@ module CWRCPerserver
 
   # Iterate via markers
   # https://github.com/ruby-openstack/ruby-openstack/blob/d9c8aa19488062e483771a9168d24f2626fe688b/lib/openstack/swift/container.rb#L100
-  swift_objs = swift_container.objects_detail
+  swift_objs = swift_container.objects
   while swift_objs.count < swift_container.container_metadata[:count].to_i
-    swift_objs = swift_objs.merge(swift_container.objects_detail(marker: swift_objs.keys.last))
+    swift_objs = swift_objs.merge(swift_container.objects(marker: swift_objs.keys.last))
   end
```
Comment (jefferya) [inline cwrc_audit_report.rb:99]: refactor: `last-mod-timestamp` metadata not returned by `objects_detail` call therefor refactor to use the more succinct `objects` call returning a array as opposed to a hash.

File: cwrc_common.rb [hunk 2]
```diff
@@ -85,12 +85,13 @@ def self.download_cwrc_obj(cookie, cwrc_obj, cwrc_file)
...
         elsif response.is_a? Net::HTTPServerError
-          raise Net::HTTPServerError.new("Failed request #{obj_path} with http status #{response.code}", response.code)
+          raise Net::HTTPError.new("Failed request #{obj_path} with http status #{response.code}", response.code)
         else
           raise Net::HTTPError.new("Failed request #{obj_path} with http status #{response.code}", response.code)
         end
       end
-    rescue Net::ReadTimeout,
+    rescue CWRCArchivingError,
+           Net::ReadTimeout,
```
Comment (jefferya) [inline cwrc_common.rb:94]: - fix bug related to exception handling: `HTTPServerError` is not an exception.
- add `CWRCArchivingError` to the list of exceptions that yield a retry

**Review by weiweishi — APPROVED** [review]
LGTM!
